name: CI

on:
  push:
    branches:
      - "main"

jobs:
  build-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["8.3"]
        engine: ["fpm","apache"]
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./${{ matrix.version }}/${{ matrix.engine }}/
          push: true
          tags: "idlemoments/php:latest-${{ matrix.engine }}"

      - name: Build and push Docker dev image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./${{ matrix.version }}/${{ matrix.engine }}/dev/
          push: true
          tags: "idlemoments/php:latest-${{ matrix.engine }}-dev"

  build-main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["8.3", "8.2", "8.1", "8.0", "7.4", "7.3", "7.2", "7.1", "5.6"]
        engine: ["fpm","apache"]
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./${{ matrix.version }}/${{ matrix.engine }}/
          push: true
          tags: "idlemoments/php:${{ matrix.version }}-${{ matrix.engine }}"

      - name: Build and push Docker dev image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./${{ matrix.version }}/${{ matrix.engine }}/dev/
          push: true
          tags: "idlemoments/php:${{ matrix.version }}-${{ matrix.engine }}-dev"
          