name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build-main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image_tag: "fpm-latest"
            context: "./8.3/fpm/"

          - image_tag: "apache-latest"
            context: "./8.3/fpm/"

          - image_tag: "8.3-fpm"
            context: "./8.3/fpm/"
          
          - image_tag: "8.3-apache"
            context: "./8.3/apache/"
          
          - image_tag: "8.2-fpm"
            context: "./8.2/fpm/"

          - image_tag: "8.2-apache"
            context: "./8.2/apache/"

          - image_tag: "8.1-fpm"
            context: "./8.1/fpm/"
          
          - image_tag: "8.1-apache"
            context: "./8.1/apache/"

          - image_tag: "8.0-fpm"
            context: "./8.0/fpm/"

          - image_tag: "8.0-apache"
            context: "./8.0/apache/"

          - image_tag: "7-fpm"
            context: "./7.4/fpm/"
          
          - image_tag: "7-apache"
            context: "./7.4/apache/"

          - image_tag: "7.4-fpm"
            context: "./7.4/fpm/"
          
          - image_tag: "7.4-apache"
            context: "./7.4/apache/"

          - image_tag: "7.3-fpm"
            context: "./7.3/fpm/"
          
          - image_tag: "7.3-apache"
            context: "./7.3/apache/"

          - image_tag: "7.2-fpm"
            context: "./7.2/fpm/"
          
          - image_tag: "7.2-apache"
            context: "./7.2/apache/"

          - image_tag: "7.1-fpm"
            context: "./7.1/fpm/"
          
          - image_tag: "7.1-apache"
            context: "./7.1/apache/"

          - image_tag: "7.0-fpm"
            context: "./7.0/fpm/"
          
          - image_tag: "7.0-apache"
            context: "./7.0/apache/"

          - image_tag: "5.6-fpm"
            context: "./5.6/fpm/"
          
          - image_tag: "5.6-apache"
            context: "./5.6/apache/"

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ matrix.context }}
          push: true
          tags: "idlemoments/php:${{ matrix.image_tag }}"

  build-dev:
    runs-on: ubuntu-latest
    needs: build-main
    strategy:
      matrix:
        include:
          - image_tag: "fpm-latest-dev"
            context: "./8.3/fpm/dev"

          - image_tag: "apache-latest-dev"
            context: "./8.3/fpm/dev"

          - image_tag: "8.3-fpm-dev"
            context: "./8.3/fpm/dev"

          - image_tag: "8.3-apache-dev"
            context: "./8.3/apache/dev"

          - image_tag: "8.2-fpm-dev"
            context: "./8.2/fpm/dev"

          - image_tag: "8.2-apache-dev"
            context: "./8.2/apache/dev"

          - image_tag: "8.1-fpm-dev"
            context: "./8.1/fpm/dev"
          
          - image_tag: "8.1-apache-dev"
            context: "./8.1/apache/dev"

          - image_tag: "8.0-fpm-dev"
            context: "./8.0/fpm/dev"
          
          - image_tag: "8.0-apache-dev"
            context: "./8.0/apache/dev"

          - image_tag: "7-fpm-dev"
            context: "./7.4/fpm/dev"
          
          - image_tag: "7-apache-dev"
            context: "./7.4/apache/dev"

          - image_tag: "7.4-fpm-dev"
            context: "./7.4/fpm/dev"
          
          - image_tag: "7.4-apache-dev"
            context: "./7.4/apache/dev"

          - image_tag: "7.3-fpm-dev"
            context: "./7.3/fpm/dev"
          
          - image_tag: "7.3-apache-dev"
            context: "./7.3/apache/dev"

          - image_tag: "7.2-fpm-dev"
            context: "./7.2/fpm/dev"
          
          - image_tag: "7.2-apache-dev"
            context: "./7.2/apache/dev"

          - image_tag: "7.1-fpm-dev"
            context: "./7.1/fpm/dev"
          
          - image_tag: "7.1-apache-dev"
            context: "./7.1/apache/dev"

          - image_tag: "7.0-fpm-dev"
            context: "./7.0/fpm/dev"
          
          - image_tag: "7.0-apache-dev"
            context: "./7.0/apache/dev"

          - image_tag: "5.6-fpm-dev"
            context: "./5.6/fpm/dev"
          
          - image_tag: "5.6-apache-dev"
            context: "./5.6/apache/dev"

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ matrix.context }}
          push: true
          tags: "idlemoments/php:${{ matrix.image_tag }}"
